# Lab1

In [3]:
import pandas as pd

covid_data = pd.read_csv('s3://ia340-2025-fall-wei-demo-5465148971/data.csv')

covid_data.head()

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:298: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [5]:
crime_data = pd.read_csv('s3://ia340-2025-fall-wei-demo-5465148971/Crime_Incidents_in_2025.csv')

crime_data.head()

,X,Y,CCN,REPORT_DAT,SHIFT,METHOD,OFFENSE,BLOCK,XBLOCK,YBLOCK,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,400588.4650,129470.0424,5131706,2025/02/05 05:00:00+00,MIDNIGHT,GUN,HOMICIDE,800 - 899 BLOCK OF XENIA STREET SE,400588.464990,129470.042358,...,009801 1,9801.0,Precinct 121,38.833020,-76.993222,NaN,2005/09/27 07:25:00+00,2005/09/27 07:26:00+00,786940029,NaN
1,405684.5761,135633.8979,10133557,2025/06/30 04:00:00+00,MIDNIGHT,GUN,HOMICIDE,4600 - 4699 BLOCK OF A STREET SE,405684.576067,135633.897851,...,009906 1,9906.0,Precinct 104,38.888528,-76.934478,NaN,2010/09/15 00:45:00+00,2010/09/14 04:00:00+00,786940034,NaN
2,397581.8300,141846.4300,25079053,2025/05/27 22:19:32+00,EVENING,OTHERS,ROBBERY,4400 - 4499 BLOCK OF IOWA AVENUE NW,397581.830000,141846.430000,...,002501 1,2501.0,Precinct 48,38.944508,-77.027895,NaN,2025/05/27 21:11:00+00,2025/05/27 22:18:00+00,786942870,NaN
3,399215.8700,138751.2000,25079273,2025/08/11 17:39:31+00,DAY,OTHERS,ROBBERY,1800 - 2199 BLOCK OF NORTH CAPITOL STREET,399215.870000,138751.200000,...,003302 1,3302.0,Precinct 19,38.916628,-77.009042,NaN,2025/05/28 07:40:00+00,2025/05/28 07:45:00+00,786944170,NaN
4,397700.5000,137976.2500,25421607,2025/05/05 18:31:00+00,DAY,OTHERS,THEFT/OTHER,1000 - 1099 BLOCK OF P STREET NW,397700.500000,137976.250000,...,004901 3,4901.0,Precinct 18,38.909644,-77.026513,NaN,2025/05/04 14:45:00+00,2025/05/04 14:50:00+00,786944171,NaN